export const FIELD_HELP: Record<string, string> = {
  age: "Age in years at the time of the census.",
  workclass: "Type of employer.",
  education: "Highest level of schooling completed.",
  "education-num":
    "Years of education completed, on a 1–16 scale matching the Education field (e.g. HS-grad ≈ 9, Bachelors ≈ 13).",
  "marital-status": "Marital status recorded at the time of the census.",
  occupation: "General category of job duties, not a specific job title.",
  relationship: "The person's role within their household.",
  race: "Race as recorded in the 1994 census categories.",
  sex: "Sex as recorded in the 1994 census (binary only — the dataset does not include other categories).",
  "capital-gain": "Profit from investments (e.g. stocks, property) in the past year.",
  "capital-loss": "Investment losses in the past year.",
  "hours-per-week": "Average hours worked per week.",
  "native-country": "Country of birth.",
};

export const OPTION_HELP: Record<string, Record<string, string>> = {
  workclass: {
    "?": "Not recorded in the original data.",
    "Federal-gov": "Employed by the U.S. federal government.",
    "Local-gov": "Employed by local (city/county) government.",
    "Never-worked": "Has never held a job.",
    Private: "Employed by a private-sector company.",
    "Self-emp-inc": "Self-employed, incorporated business.",
    "Self-emp-not-inc": "Self-employed, not incorporated.",
    "State-gov": "Employed by state government.",
    "Without-pay": "Works without pay, e.g. for a family business.",
  },
  education: {
    Preschool: "Preschool only.",
    "1st-4th": "Highest grade completed: 1st–4th grade.",
    "5th-6th": "Highest grade completed: 5th–6th grade.",
    "7th-8th": "Highest grade completed: 7th–8th grade.",
    "9th": "Highest grade completed: 9th grade.",
    "10th": "Highest grade completed: 10th grade.",
    "11th": "Highest grade completed: 11th grade.",
    "12th": "Highest grade completed: 12th grade, no diploma.",
    "HS-grad": "High school graduate.",
    "Some-college": "Attended college, no degree completed.",
    "Assoc-voc": "Associate degree, vocational track.",
    "Assoc-acdm": "Associate degree, academic track.",
    Bachelors: "Bachelor's degree.",
    Masters: "Master's degree.",
    "Prof-school": "Professional school, e.g. law or medicine.",
    Doctorate: "Doctoral degree.",
  },
  "marital-status": {
    Divorced: "Legally divorced.",
    "Married-AF-spouse": "Married to a spouse in the armed forces.",
    "Married-civ-spouse": "Married to a civilian spouse.",
    "Married-spouse-absent": "Married, but spouse not present in the household.",
    "Never-married": "Never married.",
    Separated: "Legally separated.",
    Widowed: "Widowed.",
  },
  occupation: {
    "?": "Not recorded.",
    "Adm-clerical": "Administrative or clerical work.",
    "Armed-Forces": "Military service.",
    "Craft-repair": "Skilled trade or repair work.",
    "Exec-managerial": "Executive or managerial role.",
    "Farming-fishing": "Farming or fishing work.",
    "Handlers-cleaners": "Manual handling or cleaning work.",
    "Machine-op-inspct": "Machine operation or inspection.",
    "Other-service": "Other service-industry work.",
    "Priv-house-serv": "Private household service, e.g. domestic work.",
    "Prof-specialty": "Professional specialty, e.g. teacher, engineer.",
    "Protective-serv": "Protective service, e.g. police, security.",
    Sales: "Sales work.",
    "Tech-support": "Technical support.",
    "Transport-moving": "Transportation or moving work.",
  },
  relationship: {
    Husband: "Male spouse in the household.",
    Wife: "Female spouse in the household.",
    "Not-in-family": "Lives independently of a family unit.",
    "Own-child": "A dependent child in the household.",
    "Other-relative": "Other relative living in the household.",
    Unmarried: "Unmarried, and not the household's spouse, child, or other relative.",
  },
  "native-country": {
    "?": "Not recorded in the original data.",
  },
};

export function displayOptionLabel(value: string): string {
  return value === "?" ? "Unknown / not specified" : value;
}
